services:
  - type: web
    name: lingua-nova-backend
    env: node
    region: oregon
    plan: free
    autoDeploy: true
    buildCommand: npm install
    startCommand: node server/server.js
    healthCheckPath: /api/health
    runtime: node
    repo: https://github.com/fortunadacultura-collab/lingua-nova-react
    rootDir: .
    envVars:
      - key: NODE_ENV
        value: production
      - key: FRONTEND_URL
        sync: false
      - key: CORS_ORIGINS
        sync: false
      - key: SESSION_SECRET
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_REFRESH_SECRET
        sync: false
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: BACKEND_URL
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GITHUB_CLIENT_ID
        sync: false
      - key: GITHUB_CLIENT_SECRET
        sync: false
      - key: APKG_UPLOAD_MAX_AGE_DAYS
        value: "30"
      - key: APKG_CLEANUP_CONCURRENCY
        value: "2"
    # Optional persistent disk for uploads (requires paid plan)
    # disk:
    #   name: uploads
    #   mountPath: server/uploads
    #   sizeGB: 1